project 'MobileSwiftProject.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
# 去掉警告
inhibit_all_warnings!

target 'MobileSwiftProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftProject
pod 'SnapKit'
pod 'SwiftyJSON'
pod 'HandyJSON'
pod 'Alamofire'
pod 'Kingfisher'
pod 'Moya'
pod 'SwifterSwift'

end
